DROP TABLE funcionario;

CREATE TABLE funcionario(
    CD_FUN NUMBER(2) PRIMARY KEY,
    NM_FUN VARCHAR2(20),
    SALARIO NUMBER(10,2),
    DT_ADM date);
    
BEGIN
    INSERT INTO FUNCIONARIO VALUES (1, 'João', 10000, TO_DATE( '17/04/2000', 'DD/MM/YYYY'));
    INSERT INTO FUNCIONARIO VALUES (2, 'Claudia', 16000,  TO_DATE( '02/10/1998', 'DD/MM/YYYY'));
    INSERT INTO FUNCIONARIO VALUES (3, 'Joaquim', 5500,  TO_DATE( '10/07/2010', 'DD/MM/YYYY'));
    INSERT INTO FUNCIONARIO VALUES (4, 'Valéria', 7300,  TO_DATE( '08/06/2015', 'DD/MM/YYYY'));
    INSERT INTO FUNCIONARIO VALUES (5, 'LUIZ', 20000,  TO_DATE( '16/04/2002', 'DD/MM/YYYY'));
    commit;
    
END;

SET SERVEROUTPUT ON

DECLARE
    CURSOR C_FUNCIONARIO IS (SELECT * FROM FUNCIONARIO);
    V_FUNCIONARIO C_FUNCIONARIO%ROWTYPE;
BEGIN
    OPEN C_FUNCIONARIO;
    LOOP
        FETCH C_FUNCIONARIO INTO V_FUNCIONARIO;
        DBMS_OUTPUT.PUT_LINE('NOME:'||V_FUNCIONARIO.NM_FUN);
        DBMS_OUTPUT.PUT_LINE('SALARIO: R$'||V_FUNCIONARIO.SALARIO);
    EXIT WHEN C_FUNCIONARIO%NOTFOUND;
    
    END LOOP;
    CLOSE C_FUNCIONARIO;    
END;
